# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/docker-compose.yml"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/requirements.txt"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/requirements-dev.txt"
    schedule:
      interval: "weekly"
