# Elephant Carbon Grid Intensity Service Configuration
# Copy this file to config.yml and fill in your API tokens

# Database configuration
database:
  url: "postgresql://user:password@localhost:5432/elephant"

# Provider configuration
providers:
  electricitymaps:
    api_token: "YOUR TOKEN HERE"

# Cron job for fetching data
cron:
  interval_seconds: 300  # Default: 5 minutes
  sources:
    - region: "DE"
      provider: "bundesnetzagentur"
      primary: true # If you have multiple sources for the same region, one should be marked as primary so the api knows which to return by default
    - region: "DE"
      provider: "energycharts"
    # - region: "DE"
    #   provider: "bundesnetzagentur_all"
    # - region: "DE"
    #   provider: "electricitymaps"
    #   primary: true
    # - region: "FR"
    #   provider: "electricitymaps"

# Logging
logging:
  level: "INFO"

## If you want to allow elephant to be accessed form other apps
# CORS
# cors:
#   allow_origins:
#     - "http://localhost:5173"
#     - "http://metrics.green-coding.internal:9142"
